#! /usr/bin/env sh
### BEGIN INIT INFO
# Provides:          phonesim daemon and ofono modem for bluetooth HFS
# Description:       Starts ofono-phonesim
#                    Starts enables ofono modem and make it online
# Default-Start:     2 3 4 5
### END INIT INFO

# PATH should only include /usr/* if it runs after the mountnfs.sh script
start() {
    ofono-phonesim -p 12345 /usr/share/phonesim/default.xml &
    /usr/share/ofono/test/enable-modem;
    /usr/share/ofono/test/online-modem;
}

stop () {
    kill -9 $(pgrep -f ofono-phonesim)
    /usr/share/ofono/test/disable-modem;
}

status() {
    # phonesim_enabled=$(ps -ef | grep ofono-phonesim | grep -v grep | wc -l)
    if [[ `ps -ef | grep ofono-phonesim | grep -v grep | wc -l` == 0 ]]; then
        echo "Phonesim is not running"
        exit 1
    else
        echo "Phonesim is running"
    fi
    if [[ `/usr/share/ofono/test/list-modems | grep "Powered = 1" | wc -l` == 0 ]]; then
        echo "Modem is not enabled"
        exit 1
    else
        echo "Modem is enabled"
    fi
    if [[ `/usr/share/ofono/test/list-modems | grep "Online = 1" | wc -l` == 0 ]]; then
        echo "Modem is offline"
        exit 1
    else
        echo "Modem is online"
    fi
    exit 0
}

case $1 in
    start)
        start;
    ;;
    stop)
        stop;
    ;;
    restart)
        stop;
        start;
    ;;
    status)
        status
    ;;
    *)
        echo "Invalid command $1. Allowed commands are start, stop, restart, and status"
    ;;
esac
